### ISSUE TITLE
/recover endpoint should be synchronous

### ISSUE THREAD

**Issue by meejah** [PrivateStorageio/ZKAPAuthorizer#398]
The /recover endpoint is easier to use if it simply waits for recovery to complete (good or bad) before returning. It should take care to return proper status information too (e.g. errors etc).

**Comment by exarkun** [comment]
I remembered another reason it wasn't originally synchronous.  If it's synchronous then the encouraged usage pattern is "post to this endpoint and wait a while for the response".  This pattern doesn't suggest a behavior for "you lost your connection before you got a response".  The two obvious possibilities are (a) "start polling the status endpoint if you lose your connection" and (b) "post to this endpoint again to get hooked back up to completion notification".

If it's idempotent and async then the encouraged usage pattern is "post to this endpoint until you get an Accepted response, then poll the status endpoint until you get a success or failure result".  This pattern is robust to network failures.

(a) is more work because it just devolves to the idempotent/async pattern and you may as well not bother with the extra work to handle the synchronous result case.  (b) is maybe a little better, except you still basically have to implement a poll loop.  It might not loop as often, which is nice, but the code complexity is all still there.

This doesn't necessarily mean we shouldn't make the endpoint synchronous but I think it at least means there is some interaction with #397 - we have to make sure there is a distinction between "retry the recovery" and "hook me back up to completion notification for the recovery already started" (for (b)).

And if we eventually want more progress reporting information, client code is going to have to poll anyway.

So it looks to me more like the interaction with #397 means the synchronous version is more complexity rather than less.  Thoughts?

**Comment by meejah** [comment]
Then at least the client-polling loop is something like:
```
status = None
while status not in ("finished", "error"):
    status = await request_the_status_endpoint(status)
    update_ui(status)
```

**Comment by exarkun** [comment]
An API like 

```
GET /.../recover?after=<a>

200 OK

{"id": <b>, "stage": ...}
```

where the response doesn't happen until `<b>` != `<a>` and `<b>` changes whenever the status changes seems doable.

**Comment by meejah** [comment]
Addressed by https://github.com/PrivateStorageio/ZKAPAuthorizer/pull/410
